-- i-MAN V3 — Supabase setup
-- 1) Create a Storage bucket named: activity-photos
--    Set it to PUBLIC because website visitors need to view the gallery.
-- 2) Create your admin user(s) in Supabase Authentication > Users.
-- 3) BEFORE RUNNING THIS FILE, replace the example admin email below with the
--    exact email address(es) that are allowed to upload/edit/delete.
--
-- IMPORTANT: Never put a service_role key in the website.

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  event_date date not null,
  location text,
  category text default 'Program',
  description text,
  cover_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.event_photos (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  path text not null unique,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.events enable row level security;
alter table public.event_photos enable row level security;

-- Public visitors can read published activity data.
drop policy if exists "public read events" on public.events;
create policy "public read events" on public.events
for select to anon, authenticated using (true);

drop policy if exists "public read event photos" on public.event_photos;
create policy "public read event photos" on public.event_photos
for select to anon, authenticated using (true);

-- Replace admin@example.com in ALL policies below.
drop policy if exists "admin insert events" on public.events;
create policy "admin insert events" on public.events
for insert to authenticated
with check ((auth.jwt() ->> 'email') in ('admin@example.com'));

drop policy if exists "admin update events" on public.events;
create policy "admin update events" on public.events
for update to authenticated
using ((auth.jwt() ->> 'email') in ('admin@example.com'))
with check ((auth.jwt() ->> 'email') in ('admin@example.com'));

drop policy if exists "admin delete events" on public.events;
create policy "admin delete events" on public.events
for delete to authenticated
using ((auth.jwt() ->> 'email') in ('admin@example.com'));

drop policy if exists "admin insert event photos" on public.event_photos;
create policy "admin insert event photos" on public.event_photos
for insert to authenticated
with check ((auth.jwt() ->> 'email') in ('admin@example.com'));

drop policy if exists "admin update event photos" on public.event_photos;
create policy "admin update event photos" on public.event_photos
for update to authenticated
using ((auth.jwt() ->> 'email') in ('admin@example.com'))
with check ((auth.jwt() ->> 'email') in ('admin@example.com'));

drop policy if exists "admin delete event photos" on public.event_photos;
create policy "admin delete event photos" on public.event_photos
for delete to authenticated
using ((auth.jwt() ->> 'email') in ('admin@example.com'));

-- Storage policies. The bucket itself should be PUBLIC for viewing.
drop policy if exists "admin upload activity photos" on storage.objects;
create policy "admin upload activity photos" on storage.objects
for insert to authenticated
with check (
  bucket_id = 'activity-photos'
  and (auth.jwt() ->> 'email') in ('admin@example.com')
);

drop policy if exists "admin update activity photos" on storage.objects;
create policy "admin update activity photos" on storage.objects
for update to authenticated
using (
  bucket_id = 'activity-photos'
  and (auth.jwt() ->> 'email') in ('admin@example.com')
)
with check (
  bucket_id = 'activity-photos'
  and (auth.jwt() ->> 'email') in ('admin@example.com')
);

drop policy if exists "admin delete activity photos" on storage.objects;
create policy "admin delete activity photos" on storage.objects
for delete to authenticated
using (
  bucket_id = 'activity-photos'
  and (auth.jwt() ->> 'email') in ('admin@example.com')
);
